version: '3'
volumes:
  postgres_data:
    name: ${CONTAINER_PREFIX}postgres_data
  static_value:
    name: ${CONTAINER_PREFIX}static_value
  media_value:
    name: ${CONTAINER_PREFIX}media_value

services:
  db:
    build: ./postgres
    container_name: ${CONTAINER_PREFIX}db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ./backend
    container_name: ${CONTAINER_PREFIX}backend
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - "8000"
    volumes:
      - static_value:/static/
      - media_value:/media/
    restart: always


  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_PREFIX}nginx
    depends_on:
      - db
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_value:/static/
      - media_value:/media/
      - ./html/:/static/html/
    ports:
      - "80:80"
      - "8000:80"