version: '3'
volumes:
  postgres_data:
    name: ${CONTAINER_PREFIX}postgres_data
  es_data:
    name: ${CONTAINER_PREFIX}es
  etl_data:
    name: ${CONTAINER_PREFIX}etl
  static_value:
    name: ${CONTAINER_PREFIX}static_value
  media_value:
    name: ${CONTAINER_PREFIX}media_value

services:
  db:
    build: ./postgres
    container_name: ${CONTAINER_PREFIX}db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
#    ToDo: hide for production
    ports:
      - "5432:5432"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: ${CONTAINER_PREFIX}es
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - "9200"
    volumes:
      - es_data
    restart: always
    ports:
      - "9200:9200"

  backend:
    build: ./backend
    container_name: ${CONTAINER_PREFIX}backend
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - "8000"
    volumes:
      - static_value:/static/
      - media_value:/media/
    restart: always

  etl:
    build: ./etl
    container_name: ${CONTAINER_PREFIX}etl
    volumes:
      - etl_data:/data/
    depends_on:
      - db
      - es
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_PREFIX}nginx
    depends_on:
      - db
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_value:/static/
      - media_value:/media/
      - ./html/:/static/html/
    ports:
      - "80:80"
      - "8000:80"