# Generated by Django 3.2 on 2022-06-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('actor', 'RoleChoices.ACTOR'), ('director', 'RoleChoices.DIRECTOR'), ('writer', 'RoleChoices.WRITER')], default='actor', help_text='PersonFilmWork.role.help_text', max_length=16, verbose_name='PersonFilmWork.role'),
        ),
    ]
